routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
  return redirect('/home');
}); 

Route::get('/home', 'HomeController@index')->name('home.index');  ;

Route::get('/clients/create', 'ClientController@create')->name('clients.create');;
Route::post('/clients', 'ClientController@store')->name('clients.store');

//Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {

Route::group(['middleware' => ['role:enterprise|client']], function() {

    Route::resource('tags', 'TagController');

    Route::resource('users', 'UserController'); 
     
    Route::resource('eventActions', 'EventActionController');

    //Ajax - Tag Tracker
    Route::get('/track_tag', 'TagController@tag_tracker')->name('tag_tracker'); 
    
    Route::group(['middleware' => ['role:enterprise']], function() {

        Route::resource('statusTags', 'StatusTagController');
      
        Route::resource('statusClients', 'StatusClientController');

        Route::resource('fields', 'FieldController');

        Route::get('/clients', 'ClientController@index')->name('clients.index');
        Route::get('/clients/{client}', 'ClientController@show')->name('clients.show');
        Route::get('/clients/{client}/edit', 'ClientController@edit')->name('clients.edit');        
        Route::delete('/clients/{client}', 'ClientController@destroy')->name('clients.destroy');
        Route::patch('clients/{client}', 'ClientController@update')->name('clients.update');  

        Route::resource('enterprises', 'EnterpriseController');
   
    });   
});

Auth::routes(); // login, logout

/*    
Route::resource('statusEnterprises', 'StatusEnterpriseController');

Route::resource('messages', 'MessageController');

Route::resource('tagTypes', 'TagTypeController');

Route::resource('configs', 'ConfigController');
*/

app/Models/Config.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Config
 * @package App\Models
 * @version August 30, 2017, 5:29 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection ces
 * @property \Illuminate\Database\Eloquent\Collection cts
 * @property string name
 * @property string description
 * @property boolean is_active
 * @property string value
 */
class Config extends Model
{
    use SoftDeletes;

    public $table = 'configs';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'id',
        'name',
        'description',
        'is_active',
        'value',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'description' => 'string',
        'is_active' => 'boolean',
        'value' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'description' => 'required',
        'is_active' => 'required',
        'value' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function enterprises()
    {
        return $this->belongsToMany(\App\Models\Enterprise::class, 'ces', 'enterprise_id', 'config_id', 'value');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function tags()
    {
        return $this->belongsToMany(\App\Models\Tag::class, 'cts', 'tag_id', 'config_id', 'value');
    }
}

app/Http/Controllers/ConfigController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ConfigDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateConfigRequest;
use App\Http\Requests\UpdateConfigRequest;
use App\Repositories\ConfigRepository;
use App\Http\Controllers\AppBaseController;
use App\Exceptions\Handler;
use Response;
use Flash;
use DB;

class ConfigController extends AppBaseController
{

    /** @var  ConfigRepository */
    private $configRepository;

    public function __construct(ConfigRepository $configRepo)
    {
        $this->configRepository = $configRepo;
    }

    /**
     * Display a listing of the Config.
     *
     * @param ConfigDataTable $configDataTable
     * @return Response
     */
    public function index(ConfigDataTable $configDataTable)
    {

        return $configDataTable->render('configs.index');
    }

    public function show($id)
    {
        $config = $this->configRepository->findWithoutFail($id);

        if (empty($config)) {
            Flash::error('Config not found');

            return redirect(route('configs.index'));
        }

        return view('configs.show')->with('config', $config);
    }    
}

resources/views/configs/datatables_actions.blade.php
{!! Form::open(['route' => ['configs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('configs.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
</div>
{!! Form::close() !!}

resources/views/configs/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Is Active Field -->
<div class="form-group col-sm-12">
    {!! Form::label('is_active', 'Is Active:') !!}
    <label class="radio-inline">
        {!! Form::radio('is_active', "1", null) !!} Sim
    </label>

    <label class="radio-inline">
        {!! Form::radio('is_active', "0", null) !!} Nao
    </label>

</div>

<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('configs.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/configs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Configs</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('configs.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('configs.table')
            </div>
        </div>
    </div>
@endsection

resources/views/configs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Config
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('configs.show_fields')
                    <a href="{!! route('configs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/configs/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $config->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $config->name !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $config->description !!}</p>
</div>

<!-- Is Active Field -->
<div class="form-group">
    {!! Form::label('is_active', 'Is Active:') !!}
    <p>{!! $config->is_active !!}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{!! $config->value !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $config->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $config->updated_at !!}</p>
</div>

resources/views/configs/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection