routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
  return redirect('/home');
}); 

Route::get('/home', 'HomeController@index')->name('home.index');  ;

Route::get('/clients/create', 'ClientController@create')->name('clients.create');;
Route::post('/clients', 'ClientController@store')->name('clients.store');

//Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {

Route::group(['middleware' => ['role:enterprise|client']], function() {

    Route::resource('tags', 'TagController');

    Route::resource('users', 'UserController'); 
     
    Route::resource('eventActions', 'EventActionController');

    //Ajax - Tag Tracker
    Route::get('/track_tag', 'TagController@tag_tracker')->name('tag_tracker'); 
    
    Route::group(['middleware' => ['role:enterprise']], function() {

        Route::resource('statusTags', 'StatusTagController');
      
        Route::resource('statusClients', 'StatusClientController');

        Route::resource('fields', 'FieldController');

        Route::get('/clients', 'ClientController@index')->name('clients.index');
        Route::get('/clients/{client}', 'ClientController@show')->name('clients.show');
        Route::get('/clients/{client}/edit', 'ClientController@edit')->name('clients.edit');        
        Route::delete('/clients/{client}', 'ClientController@destroy')->name('clients.destroy');
        Route::patch('clients/{client}', 'ClientController@update')->name('clients.update');  

        Route::resource('enterprises', 'EnterpriseController');
   
    });   
});

Auth::routes(); // login, logout

/*    
Route::resource('statusEnterprises', 'StatusEnterpriseController');

Route::resource('messages', 'MessageController');

Route::resource('tagTypes', 'TagTypeController');

Route::resource('configs', 'ConfigController');
*/

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UltraTrack - Cliente</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/skins/_all-skins.min.css">
    
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

    <link href="{{ asset('css/upload_file.css') }}" rel="stylesheet"/>
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    @yield('css')
</head>

<body class="skin-purple sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>UltraTrack</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->

                                <!-- Verifica se a foto está armazenada em um site, pois quando faz o sync as imagens vão estar armazenadas no site da UltraTrack -->
                                <!-- h de http -->
                                @if(Auth::user()->picture[0] == 'h')
                                    <img src="{{Auth::user()->picture}}" class="user-image" alt="User Image"/>
                                @else
                                    <img src="{{ '/storage/'.Auth::user()->picture }}" class="user-image" alt="User Image"/>
                                @endif
                                
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    @if(Auth::user()->picture[0] == 'h')
                                        <img src="{{Auth::user()->picture}}" class="img-circle" alt="User Image"/>
                                    @else
                                        <img src="{{ '/storage/'.Auth::user()->picture }}" class="img-circle" alt="User Image"/>
                                    @endif
                                    <p>
                                        {!! Auth::user()->name !!}
                                        <small>Usuário desde {!! Auth::user()->created_at->format('d-m-Y') !!}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{!! route('users.index')!!}" class="btn btn-default btn-flat">Configurações</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sair
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
        <strong>Copyright © {{date("Y")}} <a href="https://pandoapps.com.br/">Pandô APPs</a></strong>
        </footer>


@else
    @include('../home_site.blade.php')
    @endif
    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script type="text/javascript" src="{!! asset('js/select2.js') !!}"></script>

    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/js/app.min.js"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu_client.blade.php
<br>

<li class="{{ Request::is('tags*') ? 'active' : '' }}">
    <a href="{!! url('/')  !!}"><i class="fa fa-map"></i><span>Página Inicial</span></a>
</li>

<li class="{{ Request::is('tags*') ? 'active' : '' }}">
<a href="{!! route('tags.index') !!}"><i class="glyphicon glyphicon-map-marker"></i><span>Minhas Tags</span></a>

resources/views/layouts/menu_enterprise.blade.php
<br>

<li class="{{ Request::is('tags*') ? 'active' : '' }}">
    <a href="{!! url('/')  !!}"><i class="fa fa-map"></i><span>Página Inicial</span></a>
</li>
<ul class="sidebar-menu tree" data-widget="tree">
    <li class="treeview">
        <a href="#"><i class="glyphicon glyphicon-map-marker"></i> <span>Tags</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li class="{{ Request::is('tags*') ? 'active' : '' }}">
                <a href="{!! route('tags.index') !!}"><i class="glyphicon glyphicon-pushpin"></i><span>Minhas Tags</span></a>
            </li>

            <li class="{{ Request::is('fields*') ? 'active' : '' }}">
                <a href="{!! route('fields.index') !!}"><i class="glyphicon glyphicon-edit"></i><span>Campos adicionais</span></a>
            </li>
        </ul>
    </li>

    <li class="treeview menu-open">
        <a href="#"><i class="fa  fa-users"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li class="{{ Request::is('clients*') ? 'active' : '' }}">
                <a href="{!! route('clients.index') !!}"><i class="fa fa-list"></i><span>Meus clientes</span></a>
            </li>

            <li class="{{ Request::is('statusClients*') ? 'active' : '' }}">
                <a href="{!! route('statusClients.index') !!}"><i class="glyphicon glyphicon-wrench"></i><span>Status dos Clientes</span></a>
            </li> 
        </ul>
    </li>
</ul>

<li class="{{ Request::is('enterprises*') ? 'active' : '' }}">
    <a href="{!! route('enterprises.index') !!}"><i class="glyphicon glyphicon-paperclip"></i><span>Meus dados cadastrais</span></a>
</li>

<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{!! route('users.create') !!}"><i class="glyphicon glyphicon-check"></i><span>Cadastrar outro usuário da<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; empresa</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/Home_files/logo.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>UltraTrack</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
            </div>
        </div>

        <!-- search form (Optional)
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>  -->
        <!-- Sidebar Menu -->
       
        @role('enterprise')

            <ul class="sidebar-menu">
                @include('layouts.menu_enterprise')
            </ul>

        @endrole

        @role('client')

            <ul class="sidebar-menu">
                @include('layouts.menu_client')
            </ul>
                
        @endrole

        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>